#!/bin/sh -eu

# grep input/output file from 'problemURL' in current directory, generated by makeDir.sh

scriptDir=$(cd $(dirname $0); pwd;)
cd ${scriptDir}

errorMsg1="'problemURL' file not found in current directory."
errorMsg2="'problemURL' is not AtCoder url."

[ -f "${scriptDir}/problemURL" ]  || { echo ${errorMsg1}; exit; }
[ ! $(cat ${scriptDir}/problemURL | grep https://atcoder.jp ) = "" ] || { echo ${errorMsg2}; exit; }

# download problem page, then clip input-output area as inout
curl -s $(cat ${scriptDir}/problemURL) | egrep -A100 "(入力|出力)例" | sed -e "s/[\r\n]//g" | sed 's/\&amp;/&/g; s/\&lt;/</g; s/\&gt;/>/g; s/\&quot;/"/g; s/\&#39;/'"'"'/g' > inout

# count number of input-output pair
inoutNum=`cat ${scriptDir}/inout | grep 入力例 | grep -c ^`

for i in `seq 1 $inoutNum`;
do
	# from inout, generate ${i}in and ${i}out
	cat ${scriptDir}/inout | sed -n "/入力例 $i/,/<\/pre/p" | sed -e 's/.*pre>//g; $d' > ${i}"in"
	cat ${scriptDir}/inout | sed -n "/出力例 $i/,/<\/pre/p" | sed -e 's/.*pre>//g; $d' > ${i}out

	# if ${i}out is 1 line, rename ${i}in, set out info filename.( replace " " as @ )
	if [ $(cat ${i}out | grep -c ^ ) -eq 1 ]; then
		out=`cat ${i}out | sed "s; ;@;g"`
		mv ${i}"in" ${i}inout_${out}
		rm ${i}out
	fi
done

rm inout
